{
    "AlonzoGenesisFile": "alonzo-genesis.json",
    "AlonzoGenesisHash": "97b90bd22637a930eb641c2ddd685bc9f582bbb52b99167c43d971047ffa4934",
    "ByronGenesisFile": "byron/genesis.json",
    "ConwayGenesisFile": "conway-genesis.json",
    "ConwayGenesisHash": "7f194cd5cfb354da4a8ea0adb28646b064864ff0329e361658c5ea2b7242dba2",
    "EnableLogMetrics": false,
    "EnableLogging": true,
    "EnableP2P": false,
    "ExperimentalHardForksEnabled": true,
    "ExperimentalProtocolsEnabled": true,
    "LastKnownBlockVersion-Alt": 0,
    "LastKnownBlockVersion-Major": 9,
    "LastKnownBlockVersion-Minor": 0,
    "MaxConcurrencyBulkSync": 1,
    "MaxConcurrencyDeadline": 2,
    "PBftSignatureThreshold": 0.6,
    "Protocol": "Cardano",
    "RequiresNetworkMagic": "RequiresMagic",
    "ShelleyGenesisFile": "shelley-genesis.json",
    "SocketPath": "db/node.socket",
    "TestAllegraHardForkAtEpoch": 0,
    "TestAlonzoHardForkAtEpoch": 0,
    "TestBabbageHardForkAtEpoch": 0,
    "TestConwayHardForkAtEpoch": 0,
    "TestMaryHardForkAtEpoch": 0,
    "TestShelleyHardForkAtEpoch": 0,
    "TraceBlockFetchClient": false,
    "TraceBlockFetchDecisions": false,
    "TraceBlockFetchProtocol": false,
    "TraceBlockFetchProtocolSerialised": false,
    "TraceBlockFetchServer": false,
    "TraceBlockchainTime": false,
    "TraceChainDb": false,
    "TraceChainSyncBlockServer": false,
    "TraceChainSyncClient": false,
    "TraceChainSyncHeaderServer": false,
    "TraceChainSyncProtocol": false,
    "TraceConnectionManager": false,
    "TraceDnsResolver": false,
    "TraceDnsSubscription": false,
    "TraceErrorPolicy": false,
    "TraceForge": true,
    "TraceHandshake": false,
    "TraceIpSubscription": false,
    "TraceLocalChainSyncProtocol": false,
    "TraceLocalConnectionManager": false,
    "TraceLocalErrorPolicy": false,
    "TraceLocalHandshake": false,
    "TraceLocalRootPeers": false,
    "TraceLocalServer": false,
    "TraceLocalTxSubmissionProtocol": false,
    "TraceLocalTxSubmissionServer": false,
    "TraceMempool": false,
    "TraceMux": false,
    "TracePeerSelection": false,
    "TracePeerSelectionActions": false,
    "TracePublicRootPeers": false,
    "TraceServer": true,
    "TraceTxInbound": false,
    "TraceTxOutbound": false,
    "TraceTxSubmissionProtocol": false,
    "TurnOnLogMetrics": false,
    "defaultBackends": [
        "KatipBK"
    ],
    "defaultScribes": [
        [
            "FileSK",
            "logs/mainnet.log"
        ],
        [
            "StdoutSK",
            "stdout"
        ]
    ],
    "minSeverity": "Info",
    "options": {},
    "rotation": {
        "rpKeepFilesNum": 3,
        "rpLogLimitBytes": 50000000,
        "rpMaxAgeHours": 24
    },
    "setupBackends": [
        "KatipBK"
    ],
    "setupScribes": [
        {
            "scFormat": "ScJson",
            "scKind": "FileSK",
            "scName": "logs/node.log"
        },
        {
            "scFormat": "ScJson",
            "scKind": "StdoutSK",
            "scName": "stdout"
        }
    ]
}
