{
    "AlonzoGenesisFile": "alonzo-genesis.json",
    "AlonzoGenesisHash": "d8bd3e70ce80346b7cd3e291ba3bb827d5203b7887fc6f92bfb7a4cad6469d3f",
    "ByronGenesisFile": "byron/genesis.json",
    "ByronGenesisHash": "0fb29025dd88674dfcb7bf310862f28faf0f1cd1c6da35a17e10acd69e318dc4",
    "ConwayGenesisFile": "conway-genesis.json",
    "ConwayGenesisHash": "dcc5960d67d7113062aea37196136df6a634a9c4bc080b4462910155a4fdcd02",
    "EnableLogMetrics": false,
    "EnableLogging": true,
    "EnableP2P": false,
    "ExperimentalHardForksEnabled": true,
    "ExperimentalProtocolsEnabled": true,
    "LastKnownBlockVersion-Alt": 0,
    "LastKnownBlockVersion-Major": 9,
    "LastKnownBlockVersion-Minor": 0,
    "MaxConcurrencyBulkSync": 1,
    "MaxConcurrencyDeadline": 2,
    "PBftSignatureThreshold": 0.6,
    "Protocol": "Cardano",
    "RequiresNetworkMagic": "RequiresMagic",
    "ShelleyGenesisFile": "shelley-genesis.json",
    "ShelleyGenesisHash": "a660c3c2f8bb5ed8a1dcde3424c26452bac83b6103bbbb479172fe785ac2a5ef",
    "SocketPath": "db/node.socket",
    "TestAllegraHardForkAtEpoch": 0,
    "TestAlonzoHardForkAtEpoch": 0,
    "TestBabbageHardForkAtEpoch": 0,
    "TestConwayHardForkAtEpoch": 0,
    "TestMaryHardForkAtEpoch": 0,
    "TestShelleyHardForkAtEpoch": 0,
    "TraceBlockFetchClient": false,
    "TraceBlockFetchDecisions": false,
    "TraceBlockFetchProtocol": false,
    "TraceBlockFetchProtocolSerialised": false,
    "TraceBlockFetchServer": false,
    "TraceBlockchainTime": true,
    "TraceChainDb": true,
    "TraceChainSyncBlockServer": false,
    "TraceChainSyncClient": false,
    "TraceChainSyncHeaderServer": false,
    "TraceChainSyncProtocol": false,
    "TraceConnectionManager": true,
    "TraceDnsResolver": true,
    "TraceDnsSubscription": true,
    "TraceErrorPolicy": true,
    "TraceForge": true,
    "TraceHandshake": false,
    "TraceIpSubscription": true,
    "TraceLocalChainSyncProtocol": false,
    "TraceLocalConnectionManager": false,
    "TraceLocalErrorPolicy": true,
    "TraceLocalHandshake": false,
    "TraceLocalRootPeers": true,
    "TraceLocalServer": false,
    "TraceLocalTxSubmissionProtocol": false,
    "TraceLocalTxSubmissionServer": false,
    "TraceMempool": true,
    "TraceMux": false,
    "TracePeerSelection": true,
    "TracePeerSelectionActions": true,
    "TracePublicRootPeers": true,
    "TraceServer": true,
    "TraceTxInbound": false,
    "TraceTxOutbound": false,
    "TraceTxSubmissionProtocol": false,
    "TurnOnLogMetrics": false,
    "defaultBackends": [
        "KatipBK"
    ],
    "defaultScribes": [
        [
            "FileSK",
            "logs/mainnet.log"
        ],
        [
            "StdoutSK",
            "stdout"
        ]
    ],
    "minSeverity": "Debug",
    "options": {},
    "rotation": {
        "rpKeepFilesNum": 3,
        "rpLogLimitBytes": 5000000,
        "rpMaxAgeHours": 24
    },
    "setupBackends": [
        "KatipBK"
    ],
    "setupScribes": [
        {
            "scFormat": "ScJson",
            "scKind": "FileSK",
            "scName": "logs/node.log"
        },
        {
            "scFormat": "ScJson",
            "scKind": "StdoutSK",
            "scName": "stdout"
        }
    ]
}
